# Run "npm run server" in a separate terminal in books directory 
#Get all books
GET http://localhost:3001/books HTTP/1.1 
Content-Type: application/json

###
# Create a book
Content-Type: application/json

{
    "title": "Harry Potter"
}

###
# Update a book by ID
PUT http://localhost:3001/books/1 HTTP/1.1
Content-Type: application/json

{
    "title": "Eragon"
}

###
# Delete a book by ID
DELETE http://localhost:3001/books/2 HTTP/1.1
Content-Type: application/json